import { useState } from 'react';
import { Link } from 'react-router-dom';
import { MarkdownContent } from '../../components/MarkdownContent';
import { exercises, lessons } from './content';
import { attentionExample, ga2Config, parameterCounts, positional, toyTokens, toyX } from './math';
import type { Config } from './math';
import './visual-lab.css';

const fmt = (n: number) => Number.isInteger(n) ? n.toLocaleString('en-IN') : n.toFixed(4);
function Reading({ text }: { text: string }) { return <MarkdownContent markdown={text} className="lab-reading" />; }
function Matrix({ title, rows, labels }: { title: string; rows: number[][]; labels?: string[] }) {
  return <div className="lab-matrix"><h4>{title}</h4><table><tbody>{rows.map((row, i) => <tr key={i}>{labels && <th scope="row">{labels[i]}</th>}{row.map((v, j) => <td key={j}>{v === -Infinity ? '−∞' : fmt(v)}</td>)}</tr>)}</tbody></table></div>;
}
const boxes: Record<string, [string, string]> = {
 A: ['Source token embedding', 'Look up source IDs in E_s: V_s × d learned parameters. Output: B × T_s × d. Each ID selects a row; vocabulary size is not sequence length.'],
 B: ['Source positional encoding', 'Add position information to source embeddings, preserving B × T_s × d. Sinusoidal: 0 learned parameters. Learned absolute table: C × d.'],
 C: ['Target token embedding', 'Look up shifted target IDs in E_t: V_t × d parameters. Output: B × T_t × d. Training starts with BOS and true previous target tokens.'],
 D: ['Target positional encoding', 'Add position information to target embeddings. Same width d as the token embedding; adding does not double the width.'],
 E: ['Encoder self-attention', 'Q, K, V all come from this encoder layer input. Each head has T_s × T_s scores. Standard MHA: 4d² weights. Output returns to B × T_s × d.'],
 F: ['Encoder Add & Norm', 'LN(x + SelfAttention(x)). The bypass carries the sublayer input. Addition: 0 parameters; affine LayerNorm: 2d. Shape stays B × T_s × d.'],
 G: ['Encoder feed-forward network', 'At every source position: d → f → d. Two weight matrices: d × f and f × d, for 2df weights; optional biases f+d. It does not mix token positions.'],
 H: ['Encoder Add & Norm / memory', 'LN(x + FFN(x)); 2d parameters. After the final encoder block this memory supplies keys and values to cross-attention in every decoder layer.'],
 L: ['Masked decoder self-attention', 'Q, K, V come from the shifted target stream. Mask future key positions before softmax. Scores: T_t × T_t per head. Standard MHA: 4d² weights.'],
 M: ['Decoder Add & Norm', 'LN(x + MaskedSelfAttention(x)); 2d parameters. This decoder stream supplies the queries for cross-attention.'],
 O: ['Encoder–decoder cross-attention', 'Q = decoder stream × W_Q; K,V = final encoder memory × W_K,W_V. Scores: T_t × T_s per head; output: B × T_t × d. Standard equal-width MHA: 4d² weights.'],
 P: ['Decoder Add & Norm', 'LN(x + CrossAttention(x)); 2d parameters. Residual x comes from the decoder stream, not directly from the encoder memory.'],
 Q: ['Decoder feed-forward network', 'Position-wise d → f → d transformation on the target stream. 2df weights, plus f+d if biases are included. The diagram letter Q is not the query tensor Q.'],
 R: ['Decoder Add & Norm', 'LN(x + FFN(x)); 2d parameters. Output stays B × T_t × d, ready for another decoder block or the vocabulary projection.'],
 S: ['Linear vocabulary projection', 'B × T_t × d → B × T_t × V_t logits. Weight: d × V_t, optional bias V_t. Tying reuses target embeddings instead of adding another weight table.'],
 T: ['Vocabulary softmax', 'Normalize logits over V_t vocabulary entries at each target position. Probabilities sum to 1. No learned parameters. This differs from attention softmax, which normalizes over key positions.'],
 U: ['Output probabilities', 'A probability for each possible next token. Greedy decoding selects the maximum; sampling draws from a distribution. The selected token is fed back during inference.'],
};
function Architecture() {
 const [selected, select] = useState('O');
 const [names, showNames] = useState(true);
 const box = (letter: string) => <button className={`lab-node ${selected === letter ? 'selected' : ''}`} aria-pressed={selected === letter} onClick={() => select(letter)} key={letter}><b>{letter}</b><span>{names ? boxes[letter][0] : 'Identify this component'}</span></button>;
 return <div className="lab-widget"><label className="lab-check"><input type="checkbox" checked={names} onChange={e => showNames(e.target.checked)} />Show component names (turn off to test yourself)</label>
 <p className="lab-caption">Read upward ↑ · brackets repeat N times · ↶ means residual bypass around the preceding sublayer</p>
 <div className="lab-architecture">
 <div className="lab-stack"><h3>Encoder · source</h3><div className="lab-repeat"><span>N × encoder block</span>{['H','G','F','E'].map(l => <div key={l}>{box(l)}<div className="lab-arrow">↑ {['H','F'].includes(l) && '↶ residual joins here'}</div></div>)}</div>{box('B')}<div className="lab-arrow">↑ add to token vectors</div>{box('A')}<p>↑ Source IDs</p></div>
 <div className="lab-bridge">Final encoder H <strong>→ K, V → O</strong><span>Decoder M → Q → O</span><small>These arrows meet at cross-attention.</small></div>
 <div className="lab-stack"><h3>Decoder · target</h3>{['U','T','S'].map(l => <div key={l}>{box(l)}<div className="lab-arrow">↑</div></div>)}<div className="lab-repeat"><span>N × decoder block</span>{['R','Q','P','O','M','L'].map(l => <div key={l}>{box(l)}<div className="lab-arrow">↑ {['R','P','M'].includes(l) && '↶ residual joins here'}</div></div>)}</div>{box('D')}<div className="lab-arrow">↑ add to token vectors</div>{box('C')}<p>↑ Shifted target IDs</p></div>
 </div><div className="lab-callout" aria-live="polite"><h3>{selected} · {boxes[selected][0]}</h3><p>{boxes[selected][1]}</p></div>
 <p className="lab-caption">Letters match your screenshot; this readable layout shows position addition in the stream. In the original drawing B and D enter from the side. I, J, K and N are not box labels in that image.</p></div>;
}
function Embeddings() {
 const [position, setPosition] = useState(4);
 const x = [0.1,0,0.23,0.4,-0.75,1]; const pe = positional(position,6); const combined = x.map((v,i)=>v+pe[i]);
 return <div className="lab-widget"><h3>Move a token through positions</h3><p>GA 3’s six-dimensional input is fixed. Only the positional vector changes.</p><label className="lab-field">Position p = {position}<input type="range" min="0" max="20" value={position} onChange={e=>setPosition(+e.target.value)} /></label>
 <div className="lab-flow"><span>Token ID</span><b>→</b><span>Lookup E[id]</span><b>+</b><span>Position PE[p]</span><b>→</b><span>Transformer → contextual vector</span></div>
 <div className="lab-scroll"><table><thead><tr><th>Coordinate j</th><th>Token x</th><th>Angle p / 10000^(2i/6)</th><th>PE: sin / cos</th><th>x + PE</th></tr></thead><tbody>{x.map((v,i)=><tr key={i}><th>{i} ({i%2?'cos':'sin'})</th><td>{v}</td><td>{fmt(position / 10000 ** (2*Math.floor(i/2)/6))}</td><td>{fmt(pe[i])}</td><td>{fmt(combined[i])}</td></tr>)}</tbody></table></div>
 <svg className="lab-vector" viewBox="0 0 600 160" role="img" aria-label="Signed positional coordinate bars, numerical values in the table above"><line x1="20" x2="580" y1="75" y2="75" stroke="currentColor"/>{pe.map((v,i)=><g key={i}><rect x={35+i*94} y={v>0?75-v*50:75} width="45" height={Math.abs(v)*50} fill={i%2?'#0f766e':'#2457a7'}/><text x={55+i*94} y="148" textAnchor="middle">j={i}</text></g>)}</svg>
 <div className="lab-callout" aria-live="polite">Sum(x + PE) = <b>{fmt(combined.reduce((a,b)=>a+b,0))}</b> · Squared norm of PE = <b>{fmt(pe.reduce((a,b)=>a+b*b,0))}</b> at every position. Blue bars: sine; teal bars: cosine.</div></div>;
}
function Attention() {
 const [causal, setCausal] = useState(false); const [scaled, setScaled] = useState(true); const [row, setRow] = useState(0); const [step, setStep] = useState(0);
 const a = attentionExample(causal, scaled);
 const stages = ['1 · Project','2 · Dot products','3 · Scale & mask','4 · Softmax','5 · Mix values'];
 return <div className="lab-widget"><h3>Calculate “learn easy math”</h3><p>Quiz 1 example, transposed to token rows. WQ = WK = identity; WV swaps the two coordinates. Batch 1, head 1, dₖ = 2.</p>
 <div className="lab-controls"><label className="lab-check"><input type="checkbox" checked={causal} onChange={e=>setCausal(e.target.checked)}/>Causal mask</label><label className="lab-check"><input type="checkbox" checked={scaled} onChange={e=>setScaled(e.target.checked)}/>Divide scores by √2</label><label className="lab-field">Query row<select value={row} onChange={e=>setRow(+e.target.value)}>{toyTokens.map((t,i)=><option value={i} key={t}>{t}</option>)}</select></label></div>
 <div className="lab-controls">{stages.map((s,i)=><button className="btn btn-sm" aria-pressed={step===i} onClick={()=>setStep(i)} key={s}>{s}</button>)}</div>
 <div className="lab-matrices">
 {step===0 && <><Matrix title="X = Q = K (3 × 2)" rows={toyX} labels={toyTokens}/><Matrix title="V = X WV (3 × 2)" rows={a.values} labels={toyTokens}/></>}
 {step===1 && <Matrix title="Raw QKᵀ (3 × 3); columns: learn, easy, math" rows={a.scores} labels={toyTokens}/>}
 {step===2 && <Matrix title="Scores after scaling / masking" rows={a.logits} labels={toyTokens}/>}
 {step===3 && <Matrix title="A: row-wise probabilities" rows={a.weights} labels={toyTokens}/>}
 {step===4 && <><Matrix title="V: information being mixed" rows={a.values} labels={toyTokens}/><Matrix title="Z = AV (3 × 2)" rows={a.output} labels={toyTokens}/></>}
 </div><h4>Attention from “{toyTokens[row]}” → each key</h4><div className="lab-bars">{a.weights[row].map((v,j)=><div className="lab-bar-row" key={j}><span>{toyTokens[j]}</span><div><i style={{width:`${v*100}%`}} /></div><b>{(v*100).toFixed(2)}%</b></div>)}</div>
 <div className="lab-callout" aria-live="polite"><p>First dot product in this row: [{toyX[row].join(', ')}] · [1, 0] = {a.scores[row][0]}.</p><p>Output for “{toyTokens[row]}” = {a.weights[row].map((w,j)=>`${w.toFixed(4)} × [${a.values[j].join(', ')}]`).join(' + ')} = <b>[{a.output[row].map(v=>v.toFixed(4)).join(', ')}]</b>.</p><p>Weights total {a.weights[row].reduce((s,v)=>s+v,0).toFixed(4)}. Masked future tokens get exactly zero.</p></div></div>;
}
function Shapes() {
 const [length, setLength] = useState(6); const [heads, setHeads] = useState(4); const [batch, setBatch] = useState(2); const [causal, setCausal] = useState(true);
 return <div className="lab-widget"><h3>Inspect the mask and its axes</h3><div className="lab-controls">{[['Tokens T',length,setLength,2,12],['Heads h',heads,setHeads,1,8],['Batch B',batch,setBatch,1,8]].map(([label,value,set,min,max])=><label className="lab-field" key={String(label)}>{String(label)} = {Number(value)}<input type="range" min={Number(min)} max={Number(max)} value={Number(value)} onChange={e=>(set as (n:number)=>void)(+e.target.value)}/></label>)}<label className="lab-check"><input type="checkbox" checked={causal} onChange={e=>setCausal(e.target.checked)}/>Causal (otherwise bidirectional)</label></div>
 <p>Rows = query positions; columns = key positions. 0 means no added penalty; −∞ forbids attention.</p><div className="lab-scroll"><table className="lab-mask"><thead><tr><th>Q ↓ / K →</th>{Array.from({length},(_,j)=><th key={j}>{j}</th>)}</tr></thead><tbody>{Array.from({length},(_,i)=><tr key={i}><th>{i}</th>{Array.from({length},(_,j)=><td key={j} className={causal&&j>i?'blocked':'allowed'}>{causal&&j>i?'−∞':'0'}</td>)}</tr>)}</tbody></table></div>
 <div className="lab-callout" aria-live="polite"><p>One mask: {length} × {length} = {length**2} entries. Forbidden: {causal?length*(length-1)/2:0}. Allowed: {causal?length*(length+1)/2:length**2}.</p><p>All dense attention scores: B × h × T × T = {batch} × {heads} × {length} × {length} = <b>{batch*heads*length**2}</b>.</p><p>For d=128, final output: [{batch}, {length}, 128] = <b>{batch*length*128}</b> values. This does not acquire a head axis after heads are combined.</p></div>
 <div className="lab-flow"><span>Input: [BOS] I like tea</span><b>→ causal model →</b><span>Labels: I like tea [EOS]</span></div></div>;
}
function Parameters() {
 const [c, set] = useState<Config>(ga2Config); const p=parameterCounts(c);
 const update = (key: keyof Config, value: number | string | boolean) => set(old=>({...old,[key]:value}));
 const valid = c.d%c.heads===0;
 const fields: [keyof Config,string,number,number][] = [['d','Model width d',8,1024],['heads','Heads h',1,32],['ff','FFN width f',8,4096],['layers','Layers N (per stack)',1,24],['source','Source vocabulary Vs',1,100000],['vocab','Target / single vocabulary V',1,100000],['context','Position capacity C',1,8192]];
 const toggles: [keyof Config,string][] = [['attentionBias','Attention biases (+4d per MHA)'],['ffnBias','FFN biases (+f+d per FFN)'],['outputBias','Output bias (+V)'],['learnedPosition','Learned position tables'],['tied','Tie target embedding & output weights']];
 return <div className="lab-widget"><h3>Parameter ledger</h3><p>Standard equal-width heads; affine LayerNorm; two-matrix FFN; independent layers. Includes a vocabulary head for every architecture. No extra final norm or segment table. Encoder-only here is a generic encoder + vocabulary head, not a full BERT count.</p>
 <div className="lab-controls"><button className="btn btn-sm" onClick={()=>set({...ga2Config})}>Load GA 2 example</button><label className="lab-field">Architecture<select value={c.architecture} onChange={e=>update('architecture',e.target.value)}><option value="seq2seq">Encoder + decoder</option><option value="encoder">Encoder only</option><option value="gpt">GPT-style decoder only</option></select></label></div>
 <div className="lab-input-grid">{fields.filter(([key])=>key!=='source'||c.architecture==='seq2seq').map(([key,label,min,max])=><label className="lab-field" key={key}>{label}<input type="number" min={min} max={max} step="1" value={Number(c[key])} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))update(key,Math.min(max,Math.max(min,Math.trunc(n))));}}/></label>)}</div><div className="lab-toggle-grid">{toggles.map(([key,label])=><label className="lab-check" key={key}><input type="checkbox" checked={Boolean(c[key])} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div>
 {!valid ? <p role="alert" className="lab-callout">Choose a head count that divides d. Equal-width heads cannot split {c.d} into {c.heads} integer widths.</p> : <><p>Per-head dₖ = dᵥ = <b>{c.d/c.heads}</b>. Per-head WQ shape: {c.d} × {c.d/c.heads}; WO: {c.d} × {c.d}.</p><div className="lab-scroll"><table><thead><tr><th>Component</th><th>Calculation</th><th>Parameters</th></tr></thead><tbody>
 <tr><td>One MHA</td><td>4 × {c.d}² {c.attentionBias?`+ 4 × ${c.d}`:''}</td><td>{fmt(p.mha)}</td></tr><tr><td>One FFN</td><td>2 × {c.d} × {c.ff} {c.ffnBias?`+ ${c.ff} + ${c.d}`:''}</td><td>{fmt(p.ffn)}</td></tr><tr><td>One LayerNorm</td><td>2 × {c.d}</td><td>{fmt(p.norm)}</td></tr><tr><td>Encoder / GPT-style block</td><td>MHA + FFN + 2 LN</td><td>{fmt(p.encoder)}</td></tr>{c.architecture==='seq2seq'&&<tr><td>Decoder block with cross-attention</td><td>2 MHA + FFN + 3 LN</td><td>{fmt(p.decoder)}</td></tr>}
 <tr className="lab-total"><td>Stack subtotal</td><td>{c.layers} × {c.architecture==='seq2seq'?'(encoder + decoder)':'block'}</td><td data-testid="stack-total">{fmt(p.stack)}</td></tr><tr><td>Token tables</td><td>{c.architecture==='seq2seq'?`(${c.source} + ${c.vocab})` : c.vocab} × {c.d}</td><td>{fmt(p.token)}</td></tr><tr><td>Position tables</td><td>{c.learnedPosition?`${c.architecture==='seq2seq'?2:1} × ${c.context} × ${c.d}`:'Sinusoidal: no learned weights'}</td><td>{fmt(p.position)}</td></tr><tr><td>Additional output parameters</td><td>{c.tied?'Shared weights counted above':`${c.d} × ${c.vocab}`}{c.outputBias?` + ${c.vocab} bias`:''}</td><td>{fmt(p.output)}</td></tr><tr className="lab-total"><td>Complete total</td><td>Stacks + tables + extra output</td><td>{fmt(p.total)}</td></tr>
 </tbody></table></div><div className="lab-bars">{([['Stacks',p.stack],['Token tables',p.token],['Positions',p.position],['Extra output',p.output]] as [string,number][]).map(([label,n])=><div className="lab-bar-row" key={label}><span>{label}</span><div><i style={{width:`${100*n/p.total}%`}}/></div><b>{(100*n/p.total).toFixed(1)}%</b></div>)}</div><p className="lab-caption">Try doubling h while d stays fixed: MHA parameters stay constant. Changing C only adds parameters when learned positions are enabled. Tying saves exactly d × V weights.</p></>}
 </div>;
}
function Generation() {
 const [k,setK]=useState(3); const [mode,setMode]=useState('topk');const [p,setP]=useState(0.8);
 const candidates=[['majestic',0.35],['abandoned',0.30],['historic',0.20],['but',0.07],['the',0.03],['was',0.03],['castle',0.02]] as [string,number][];
 let mass=0; const kept=candidates.filter(([,v],i)=>{const keep=mode==='greedy'?i===0:mode==='topk'?i<k:mass<p; if(keep)mass+=v;return keep;});
 return <div className="lab-widget"><h3>Vocabulary distribution → decoding rule</h3><p>Quiz 1, timestep 4. Ties use the displayed order. Sampling probabilities below are renormalized; greedy always selects its top token.</p><div className="lab-controls"><label className="lab-field">Rule<select value={mode} onChange={e=>setMode(e.target.value)}><option value="topk">Top-k</option><option value="topp">Top-p (nucleus)</option><option value="greedy">Greedy</option></select></label>{mode==='topk'&&<label className="lab-field">k = {k}<input type="range" min="1" max="7" value={k} onChange={e=>setK(+e.target.value)}/></label>}{mode==='topp'&&<label className="lab-field">p = {p.toFixed(2)}<input type="range" min="0.05" max="1" step="0.05" value={p} onChange={e=>setP(+e.target.value)}/></label>}</div><div className="lab-scroll"><table><thead><tr><th>Token</th><th>Model probability</th><th>Retained?</th><th>Decoding probability</th></tr></thead><tbody>{candidates.map(([t,v])=><tr key={t}><th>{t}</th><td>{v.toFixed(2)}</td><td>{kept.some(([s])=>s===t)?'Yes':'No'}</td><td>{kept.some(([s])=>s===t)?(v/mass).toFixed(4):'0'}</td></tr>)}</tbody></table></div><div className="lab-callout" aria-live="polite">Retained mass = {mass.toFixed(2)}. {mode==='greedy'?'Greedy selects majestic with probability 1, though its model probability is 0.35.':`For majestic: 0.35 / ${mass.toFixed(2)} = ${(0.35/mass).toFixed(4)}.`}</div>
 <details><summary>Why greedy is not the best full sequence: tiny tree</summary><div className="lab-flow"><span>START → A (0.6) → x (0.5): 0.30</span><span>START → A (0.6) → y (0.5): 0.30</span><span>START → B (0.4) → x (0.9): 0.36</span><span>START → B (0.4) → y (0.1): 0.04</span></div><p>Greedy chooses A and scores 0.30. A width-2 beam retains A and B at step 1; at step 2 it finds B x with 0.36. Beam search is still approximate for larger trees.</p></details></div>;
}
function ExerciseCard({index,onCorrect}: {index:number;onCorrect:(i:number)=>void}) {
 const q=exercises[index]; const [answer,setAnswer]=useState(''); const [checked,check]=useState(false);const [hint,showHint]=useState(false);const [reveal,show]=useState(false);
 const normalized=answer.trim().toLowerCase(); const correct=q.tolerance!==undefined?normalized!==''&&Number.isFinite(Number(normalized))&&Math.abs(Number(normalized)-Number(q.answer))<=q.tolerance:normalized===q.answer.toLowerCase();
 return <article className="lab-exercise"><span className="lab-eyebrow">Practice {index+1} · {lessons[q.topic].title}</span><Reading text={q.question}/><form onSubmit={e=>{e.preventDefault();check(true);if(correct)onCorrect(index);}}><label className="lab-field" htmlFor={`answer-${index}`}>Your answer<input id={`answer-${index}`} autoComplete="off" value={answer} onChange={e=>{setAnswer(e.target.value);check(false);}} placeholder="Type your answer" /></label><button className="btn btn-primary" type="submit">Check answer</button><button className="btn" type="button" onClick={()=>showHint(!hint)}>Hint</button><button className="btn" type="button" onClick={()=>show(!reveal)}>{reveal?'Hide':'Show'} solution</button></form>{hint&&<p className="lab-hint">Hint: {q.hint}</p>}{checked&&<p role="status" className={correct?'lab-correct':'lab-retry'}>{correct?'Correct — now explain the reasoning.':'Not yet. Use the hint, check the requested quantity, and try again.'}</p>}{(reveal||(checked&&correct))&&<div className="lab-callout"><b>Answer: {q.answer}</b><Reading text={q.solution}/></div>}</article>;
}
export function VisualLabPage() {
 const [topic,setTopic]=useState(0);const [all,setAll]=useState(false);const [solved,setSolved]=useState<number[]>([]);
 const widgets=[null,<Architecture key="architecture"/>,<Embeddings key="embeddings"/>,<Attention key="attention"/>,<Shapes key="shapes"/>,<Parameters key="parameters"/>,<Generation key="generation"/>,null];
 const choose=(i:number)=>{setTopic(i);setAll(false);};
 return <main className="visual-lab"><header className="lab-hero"><span className="lab-eyebrow">Visual learning · GA 1–4 + Quiz 1</span><h1>See the Transformer.<br/>Then do the maths.</h1><p>A guided path from “what is this box?” to “I can calculate its shape, weights and output.” Read a little, change the diagram, then solve a few questions.</p><div className="lab-hero-meta"><span>8 short lessons</span><span>6 interactive explorations</span><span>{exercises.length} explained exercises</span></div></header>
 <div className="lab-layout"><aside><nav aria-label="Learning path" className="lab-nav">{lessons.map((l,i)=><button key={l.title} aria-current={topic===i?'step':undefined} onClick={()=>choose(i)}><span>{String(i+1).padStart(2,'0')}</span>{l.title}</button>)}</nav><p className="lab-progress">{solved.length} / {exercises.length} answered correctly this visit</p><progress aria-label="Practice questions answered correctly" value={solved.length} max={exercises.length}/><p className="lab-caption">Study at your pace. Start with lessons 1–2; calculators come after the concepts. Progress resets on page reload.</p></aside>
 <div className="lab-main"><section aria-labelledby="lesson-title"><span className="lab-eyebrow">Lesson {topic+1} of 8 · {lessons[topic].source}</span><h2 id="lesson-title">{lessons[topic].title}</h2><p className="lab-subtitle">{lessons[topic].subtitle}</p><Reading text={lessons[topic].reading}/>{widgets[topic]}</section>
 <section className="lab-practice" aria-labelledby="practice-title"><h2 id="practice-title">Try it before revealing the answer</h2><label className="lab-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Show all {exercises.length} exercises for mixed revision</label>{exercises.map((q,i)=>(all||q.topic===topic)&&<ExerciseCard key={i} index={i} onCorrect={n=>setSolved(old=>old.includes(n)?old:[...old,n])}/>)}</section>
 <div className="lab-next"><button className="btn" disabled={topic===0} onClick={()=>choose(topic-1)}>← Previous lesson</button><button className="btn btn-primary" disabled={topic===7} onClick={()=>{choose(topic+1);window.scrollTo({top:0,behavior:'instant'});}}>Next lesson →</button></div>
 <footer className="lab-sources"><h3>Return to the original questions</h3><div className="lab-controls">{['ga1','ga2','ga3','ga4','pyq-may-2026-quiz-1'].map(id=><Link className="btn btn-sm" key={id} to={`/practice/${id}`}>{id.startsWith('pyq')?'Quiz 1':id.toUpperCase()}</Link>)}</div><p>Scope: the classic Transformer taught in these assignments. Modern models can change normalization, positional methods and FFN structure, so always use the exam’s stated assumptions.</p><p>Foundational references: <a href="https://arxiv.org/abs/1706.03762">Attention Is All You Need</a> (architecture and attention); <a href="https://aclanthology.org/N19-1423/">BERT</a> (bidirectional pretraining). Derivations and numerical tools here use the course configurations.</p></footer>
 </div></div></main>;
}
